slect:
  #二次元
  - AcFun - 番剧
  - Animen 动漫平台 - news
  - Bangumi - 放送列表
  - Eventernote - 声优活动及演唱会
  - Hpoi 手办维基 - 情报
  - 东方我乐多丛志 - 文章
  - 三界异次元 - 三界异次元
  #游戏
  - 3DMGame - 新闻中心
  - 3DMGame - 游戏资讯
  - 4Gamers 新闻 - 标签
  - 4Gamers 新闻 - 分类
  - 4Gamers 新闻 - 标签
  - Epic Games Store - 免费游戏
  - GNN-tw-游戏新闻-GNN-tw-游戏新闻
  - GameRes-游资网-列表
  - GameRes-游资网-热点推荐
  - Indienova-indienova-文章
  - Nintendo-eShop-新发售游戏