# RSS更新
name: update-RSSHub

on: 
  release:
    types: [published]
  repository_dispatch:
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt
    - name: Delete Post Dir  #删除post目录
      run: | 
        rm -rf /source/_posts
    - name: Update RSS #更新
      run: | 
        python muti_work.py
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
    - name: Commit #更新日志到GitHub仓库
      run: |
        git config --global user.email AutoWakeUp@email.com
        git config --global user.name AutoWakeUp
        git add .
        git commit -m "Successfully Wake" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
    - name: Install Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli gulp-cli -g
    - name: Set SSH Key
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Cache Hexo
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
    - name: Install Npm Requirements
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install --save

    - name: Hexo Generate
      run: |
        hexo g

    - name: Deploy
      run: |
        git config --global user.name "Zfour"
        git config --global user.email "499984532@qq.com"
        hexo deploy

