# RSS更新
name: update-RSSHub

on: 
  release:
    types: [published]
  repository_dispatch:
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt
    - name: Delete Post Dir  #删除post目录
      run: | 
        rm -rf post
    - name: Update RSS #更新
      run: | 
        python muti_work.py
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
    - name: Commit #更新日志到GitHub仓库
      run: |
        git config --global user.email AutoWakeUp@email.com
        git config --global user.name AutoWakeUp
        git add .
        git commit -m "Successfully Wake" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
